#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

START_TIME=$(date "+%Y-%m-%d %H:%M:%S")
echo "🔍 [$START_TIME] commit 이전에 lint 규칙을 적용합니다..."
if npx lint-staged; then
  END_TIME=$(date "+%Y-%m-%d %H:%M:%S")
  echo "✅ [$END_TIME] 모든 lint 규칙이 성공적으로 적용되었습니다."
  exit 0
else
  END_TIME=$(date "+%Y-%m-%d %H:%M:%S")
  echo "❌ [$END_TIME] lint 규칙 검사에서 오류가 발생했습니다."
  exit 1
fi

# https://github.com/desktop/desktop/issues/17385
# husky window 미작동 시 참고할 것
# 만약에 그래도 작동이 안된다면 허스키 기본 설치를 다시 해볼 것